[build]
  publish = "public"
  command = "npm run build"
[build.environment]
  YARN_VERSION = "1.3.2"
  YARN_FLAGS = "--no-ignore-optional"
[context.production]
  environment = { NETLIFY_MAP_KEY = "AIzaSyCQVuWUGXqlhPez96eHvPjvyZTJxj8fKmY" }